extends:
  - airbnb
  - prettier
  - prettier/react

env:
  browser: true

parser: babel-eslint
parserOptions:
  ecmaVersion: 2018

plugins:
  - prettier

rules:
  curly: [error, multi-or-nest]
  eqeqeq: [error, smart]
  no-plusplus: [error, { allowForLoopAfterthoughts: true }]
  max-len: [error, {
    code: 80,
    tabWidth: 2,
    ignoreComments: false,
    ignoreTrailingComments: false,
    ignoreUrls: true,
    ignoreStrings: true,
    ignoreTemplateLiterals: true,
    ignoreRegExpLiterals: true,
  }]
  new-parens: off
  prettier/prettier: error
  react/destructuring-assignment: off
  react/prop-types: [error, { skipUndeclared: true }]

