name: CORE
description: >
  CORE is a service provided by the Knowledge Media Institute,
  based at The Open University, United Kingdom.
navigation:
  - title: Services
    path: ~services
    sections:
      - title: Access to data
        path: ~services#access-to-data
        children:
          - title: API
            path: ~services/api
          - title: Dataset
            path: ~services/dataset
          - title: SDK
            path: ~services/sdk
      - title: Content discovery
        path: ~services/discovery
        children:
          - title: CORE recommender
            path: ~services/recommender
          - title: CORE connector
            path: ~services/connector
      - title: Managing content
        path: ~services#managing-content
        children:
          - title: Repository dashboard
            path: ~services/repository-dashboard
          - title: Analytics dashboard
            path: ~services/analytics-dashboard
      - title: Support
        path: ~support
        children:
          - title: FAQs
            path: ~faq
  - title: About
    path: ~about
    children:
      - title: About CORE
        path: ~about
      - title: Blog
        path: ~blog
      - title: Contact us
        path: ~contact
footer:
  - title: Blog
    path: ~blog
  - title: Contact us
    path: ~contact
  - title: Privacy notice
    path: ~privacy
  - title: Browse
    path: ~browse
  - title: Cookies
    path: ~cookies
  - title: About CORE
    path: ~about
