name: Pull request check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: '12.x'

      - name: yarn install, build, and test
        run: |
          npm ci
          npm run build
          npm run lint
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_TARGET: server
